version: '3.8'

services:
  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
    command: tarantool /opt/tarantool/init.lua
    ports:
      - "3301:3301"

  go-app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    depends_on:
      - tarantool
